wandb_version: 1

lr:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 1.0
p:
  desc: null
  value: 113
d_model:
  desc: null
  value: 128
fn_name:
  desc: null
  value: add
frac_train:
  desc: null
  value: 0.3
num_epochs:
  desc: null
  value: 50000
save_models:
  desc: null
  value: false
save_every:
  desc: null
  value: 100
stopping_thresh:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
num_layers:
  desc: null
  value: 1
batch_style:
  desc: null
  value: full
d_vocab:
  desc: null
  value: 114
n_ctx:
  desc: null
  value: 3
d_mlp:
  desc: null
  value: 512
num_heads:
  desc: null
  value: 4
act_type:
  desc: null
  value: ReLU
device:
  desc: null
  value: cuda
use_ln:
  desc: null
  value: false
take_metrics_every_n_epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726068704
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.0
      5: 0.17.9
      6: ''
      8:
      - 3
      - 5
      12: ''
      13: windows-amd64
